---

- name: Install MySQL package
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - mysql-server
   - python-mysqldb
  when:
   ansible_os_family == "Debian"

- name: Make sure MySQL is started
  sudo: yes
  service: name=mysql state=started enabled=yes